### ISSUE TITLE
Check out

### ISSUE THREAD

**Issue by Code-Sploit** [dragonfireclient/dragonfireclient#11]
I have succeeded into making a list of active hacks on your screen. Realtime update.
You have to edit src/gui/hackList.cpp to manually add hacks to the list. I have created a different repository for my fork/version of
dragonfireclient. It's called sunclient. It includes some extra features (Not many). And the hack list.

I hope that's ok?

**Comment by LizzyFleckenstein03** [comment]
Well, I dont completely understand your way to use git. Why do you put everything into a zip archive? It makes things a lot harder and basically removes git's advantages.
I'll have a look at SunClient; However the feature is cool but everything should be dynamic; there should be some API for this. I will defintiely do this in the future, but at time I'm pretty busy with MineClone2 development and also the software of my own minetest server (Elidragon Skyblock) completely collapsed, so the Hackclient has for now a bit lower priority.

**Comment by Code-Sploit** [comment]
I renamed it to Toxiclient it's now on: https://github.com/Code-Sploit/Toxiclient

**Comment by LizzyFleckenstein03** [comment]
Still, why do you put the actual program into a .zip file? That makes merging your features impossible.

**Comment by LizzyFleckenstein03** [comment]
I added that Feature. It simply shows the active entries from the Cheat Menu in the left upper corner of the screen. I gave it a nice color animation, you might want to check it out. The CheatHUD is toggleable in the Cheat Menu.
