### ISSUE TITLE
New Movement, Combat hack

### ISSUE THREAD

**Issue by Code-Sploit** [dragonfireclient/dragonfireclient#13]
Could you please add:
1) Invwalk Description: The possibility to walk when inventory is open.
2) AlwaysLeftClick Description: If right mouse button is pressed re-route it to the left mouse button so when you rightclick it will leftlcick in the game

**Comment by LizzyFleckenstein03** [comment]
Invwalk: Use AutoForward lol its a vanilla feature (you can assign a keybind for faster access)
AlwaysLeftClick: I dont see a use for that
