### ISSUE TITLE
Scaffold + Freecam

### ISSUE THREAD

**Issue by Code-Sploit** [dragonfireclient/dragonfireclient#16]
##### Minetest version

```

```

##### OS / Hardware

Operating system: Linux Arch

##### Summary
When you turn on freecam and scaffold, and hold some blocks the scaffold hack will still place blocks under the freecam entity's feet!

##### Steps to reproduce
1) Login to a game of minetest.
2) Turn on scaffold and freecam.
3) Get some blocks and hold them
4) There you go!

**Comment by LizzyFleckenstein03** [comment]
Uhm yes, that is intentionally?

**Comment by LizzyFleckenstein03** [comment]
Freecam is meant to only move the camera!

**Comment by Code-Sploit** [comment]
But it still places blocks under your feet, on camera freecam-camera position

**Comment by LizzyFleckenstein03** [comment]
Hmm. Imma just keep pretending everything is intentional.
