### ISSUE TITLE
Build fails on MacOS

### ISSUE THREAD

**Issue by Luna-HD** [dragonfireclient/dragonfireclient#21]
100%] Linking CXX executable ../bin/minetest
Undefined symbols for architecture x86_64:
  "PcgRandom::PcgRandom(unsigned long long, unsigned long long)", referenced from:
      Sky::updateStars() in sky.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/minetest] Error 1
make[1]: *** [src/CMakeFiles/minetest.dir/all] Error 2
make: *** [all] Error 2

**Comment by randomMesh** [comment]
There's an upstream issue for this: https://github.com/minetest/minetest/issues/10858

**Comment by Minetest-j45** [comment]
@EliasFleckenstein03 the mt issue above has been closed, maybe it is possible to also close this if https://github.com/minetest/minetest/pull/10872 was added to df
