### ISSUE TITLE
One more ask

### ISSUE THREAD

**Issue by fluxionary** [dragonfireclient/dragonfireclient#24]
Please feel free to just close this or ignore it if you want; I don't want things to get heated like before. But if you could create a new windows build (w/ the version string update) and remove the old versions, I'd really appreciate it.

Thank you,

~flux

**Comment by randomMesh** [comment]
This doesn't stop those who want to use this client without the version string. This is an open source project after all.

**Comment by fluxionary** [comment]
> This doesn't stop those who want to use this client without the version string. This is an open source project after all.

Of course? But most people aren't capable of changing the version string themselves. This would act as a filter, not a complete solution to the "problem". And, it wouldn't affect how the client is used on anarchy servers.

**Comment by LizzyFleckenstein03** [comment]
Ok, I will do that.

**Comment by LizzyFleckenstein03** [comment]
Done.
