### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Sirius-Black4** [dragonfireclient/dragonfireclient#27]
I've been wondering how to use it, it wold be useful for a simple step by step explanation on how to use this client( I'm on fedora). The current guide is confusing to follow.

**Comment by realOneplustwo** [comment]
Read the README, under "Compiling". Once you have compiled, run the executable.

**Comment by Sirius-Black4** [comment]
I understand but what i was asking was a simplified version which is easy to understand on how to use it. Eg. where do we put the complied stuff and etc. .

**Comment by Sirius-Black4** [comment]
Also a youtube tutorial wold be helpful. I've seen many for windows but none for Linux.
