### ISSUE TITLE
Xray on off Feature

### ISSUE THREAD

**Issue by Sirius-Black4** [dragonfireclient/dragonfireclient#29]
I'm always frustrated when i have to turn xray on and off every time i need it from the settings and is also not mentioned in the cheat GUI. Is there a specific key to turn it on? 

If there isn't please add it, ( this issue isn't important i will close it if you want )
Thanks!

**Comment by LizzyFleckenstein03** [comment]
X-Ray should be in the Cheat GUI. If the cheat GUI does not fit onto your screen entirely, consider making cheat menu entries less high in the settings.
