### ISSUE TITLE
http://cheatdb.elidragon.com unreachable

### ISSUE THREAD

**Issue by AFCMS** [dragonfireclient/dragonfireclient#30]
http://cheatdb.elidragon.com is unreachable.
Where is he hosted? In Strasbourg? XD

**Comment by TechDudie** [comment]
Yes, the server is unreachable.

**Comment by AFCMS** [comment]
@TechDudie Was this server hosted in Strasbourg? xD

**Comment by TechDudie** [comment]
Umm idk don’t ask me I didn’t host it

**Comment by LizzyFleckenstein03** [comment]
The server is hosted at Zap hosting. However I got scammed so cheatdb will probably be offline until we find a solution (In case somebody wants to help us out, head to https://www.elidragon.com/donate/)

**Comment by LizzyFleckenstein03** [comment]
We got things sorted out now. We decided to not host Elidragon v2 Alpha on the VPS, so the other services should be unaffected. Both the Clamity wiki and CheatDB are up again.
