### ISSUE TITLE
Breaking news

### ISSUE THREAD

**Issue by pl608** [dragonfireclient/dragonfireclient#31]
##### Minetest version

```
5.4.0
```

##### OS / Hardware

Operating system: windows
##### Summary
for some reason when i log onto a server i cant break/place blocks
i can do so however if i am on a single player world

**Comment by LoneWolfHT** [comment]
Are you logging onto a server that doesn't allow hacked clients?

**Comment by pl608** [comment]
I am on Clamity Anarchy
i also tried on other servers

**Comment by AFCMS** [comment]
@pl608 A cheat make walls not pointable (you can hit entities behind the wall). Make sure this cheat isn't activated.

**Comment by LizzyFleckenstein03** [comment]
This is probably because the server uses a protection mod. It has nothing to do with dragonfireclient.

**Comment by zultron** [comment]
I had the same problem.  Turns out I'd turned on the "ThroughWalls" cheat without understanding what it does.
