### ISSUE TITLE
Add linux support

### ISSUE THREAD

**Issue by AFCMS** [dragonfireclient/dragonfireclient#32]
## Problem
I use linux.
There is no dradonfire build for linux.

## Solutions

Build dragonfire for linux

## Alternatives

?

## Additional context
?
@EliasFleckenstein03

**Comment by HimbeerserverDE** [comment]
You can build it from source in the exact same way you build regular MT

**Comment by AFCMS** [comment]
hum... It is difficult for non-developers to build something like a game engine.

**Comment by HimbeerserverDE** [comment]
Not really. Just cd to the repository root and run these commands:
```
cmake . -DRUN_IN_PLACE=TRUE
make -j$(nproc)
```

**Comment by LizzyFleckenstein03** [comment]
I use linux as well. To build dragonfire I crosscompile it. I don't see a reason to add a Linux build because compiling is pretty easy on Linux. Also, there is no buildbot for that so I'm just too lazy.
