### ISSUE TITLE
[FEATURE] Blink

### ISSUE THREAD

**Issue by ChefZander** [dragonfireclient/dragonfireclient#36]
Sends fake lag packets (like LiquidBounce) and makes it look like ur teleporting (for other ppl)

**Comment by HimbeerserverDE** [comment]
There are no lag packets

**Comment by ChefZander** [comment]
Then leave out packets (recreate the behaviour of packets when the client is lagging)

**Comment by HimbeerserverDE** [comment]
Wouldn’t it make more sense to delay some of the ack packets?

**Comment by ChefZander** [comment]
No, leave out packets (Just like with a timeout) and "teleport". This is cool
