### ISSUE TITLE
Cannot Compile Dragonfire

### ISSUE THREAD

**Issue by arydevy** [dragonfireclient/dragonfireclient#38]
![image](https://user-images.githubusercontent.com/62546648/114976213-44b21c00-9e8e-11eb-8454-3a16b2616ce8.png)
I keep Getting this error

**Comment by MistUnky** [comment]
in latest versions of minetest you need irrlichtmt installed, which you can get here:
https://github.com/minetest/irrlicht
it does not conflict w/ irrlicht installations due to being called "irrlichtmt" rather than "irrlicht" so it should not cause any problems

**Comment by Nv7-GitHub** [comment]
You need to get Irrlicht - clone https://github.com/minetest/irrlicht, `cd` into it, and do 
```
cmake . -DBUILD_SHARED_LIBS=OFF
make -j$(nproc)
make install
```
Then, run cmake, using 
```
cmake . -DIRRLICHT_INCLUDE_DIR=$PWD/../irrlicht/include -DIRRLICHT_LIBRARY=$PWD/../irrlicht/lib/<OS>/libIrrlicht.a -DRUN_IN_PLACE=TRUE
```
