### ISSUE TITLE
Linux build instructions are for vanilla from the looks of it

### ISSUE THREAD

**Issue by IITFA** [dragonfireclient/dragonfireclient#39]
So, just compiled this client and followed the instructions to the letter and ended up with the vanilla client.

For irrlicht (or similar)
git clone https://github.com/minetest/irrlicht
cd irrlicht
cmake . -DBUILD_SHARED_LIBS=ON
make -j$(nproc)

Should probably be (or similar)
git clone https://github.com/EliasFleckenstein03/dragonfireclient.git
cd dragonfireclient
git clone https://github.com/minetest/minetest_game.git games/minetest_game
cmake . -DRUN_IN_PLACE=TRUE -DIRRLICHT_LIBRARY=$PWD/irrlicht/lib/Linux/libIrrlichtMt.so -DIRRLICHT_INCLUDE_DIR=$PWD/irrlicht/include
make -j$(nproc)

**Comment by franksouza183** [comment]
That works!
