### ISSUE TITLE
Add "Give"cheats Please?

### ISSUE THREAD

**Issue by userGabby** [dragonfireclient/dragonfireclient#44]

**Comment by fisherbait** [comment]
ok...

You can't use /give or /grant or /grantme with this hacked client. That is something that doesn't change based on the client you use, you have to have permission from the server admins. 

"Oyestry anarchy" -- did you mean "Oysterity Anarchy"?

"kits" are over-glorified shulker boxes that have the exact same items in them and have been created by a player. The admins or the privs of the accounts have nothing to do with the kits or their contents. (you can't do /give kitname anyways)

**Comment by userGabby** [comment]
I changed it , will .grant work?It dosent matter with the server side right?

**Comment by fisherbait** [comment]
You don't seem to get it. You CANNOT tell the server to give/grant you items. If you could, you are either playing on a creative server or you have access to a backdoor. 

Also, if you gain access to unlimited rare items, they no longer are rare and they loose all their value. I remember on Clamity we would use diamond blocks to make tunnels through the massive watercubes at spawn. They were pretty much worthless. Same thing would happen on other servers if you could give yourself items (as you can see on creative servers).
