### ISSUE TITLE
Compilation error at Linux Mint 20

### ISSUE THREAD

**Issue by sangeet79** [dragonfireclient/dragonfireclient#46]
Scanning dependencies of target IrrlichtMt
[ 43%] Linking CXX static library ../../lib/Linux/libIrrlichtMt.a
[ 43%] Built target IrrlichtMt
Scanning dependencies of target minetest
[ 43%] Building CXX object src/CMakeFiles/minetest.dir/client/camera.cpp.o
[ 43%] Building CXX object src/CMakeFiles/minetest.dir/client/activeobjectmgr.cpp.o
[ 43%] Building CXX object src/CMakeFiles/minetest.dir/client/client.cpp.o
[ 43%] Building CXX object src/CMakeFiles/minetest.dir/client/clientenvironment.cpp.o
[ 44%] Building CXX object src/CMakeFiles/minetest.dir/client/clientlauncher.cpp.o
In file included from /home/*/*/*/minetest/src/client/game.h:70,
                 from /home/*/*/*/minetest/src/client/gameui.h:28,
                 from /home/*/*/*/minetest/src/client/client.cpp:31:
/home/*/*/*/minetest/src/irrlicht_changes/static_text.h:188:62: error: ‘irr::io::SAttributeReadWriteOptions’ has not been declared
  188 |   virtual void serializeAttributes(io::IAttributes* out, io::SAttributeReadWriteOptions* options) const;
      |                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/*/*/*/minetest/src/irrlicht_changes/static_text.h:191:63: error: ‘irr::io::SAttributeReadWriteOptions’ has not been declared
  191 |   virtual void deserializeAttributes(io::IAttributes* in, io::SAttributeReadWriteOptions* options);
      |                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
[ 44%] Building CXX object src/CMakeFiles/minetest.dir/client/clientmap.cpp.o
In file included from /home/*/*/*/minetest/src/client/game.h:70,
                 from /home/*/*/*/minetest/src/client/clientlauncher.cpp:25:
/home/*/*/*/minetest/src/irrlicht_changes/static_text.h:188:62: error: ‘irr::io::SAttributeReadWriteOptions’ has not been declared
  188 |   virtual void serializeAttributes(io::IAttributes* out, io::SAttributeReadWriteOptions* options) const;
      |                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/*/*/*/minetest/src/irrlicht_changes/static_text.h:191:63: error: ‘irr::io::SAttributeReadWriteOptions’ has not been declared
  191 |   virtual void deserializeAttributes(io::IAttributes* in, io::SAttributeReadWriteOptions* options);
      |                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
[ 44%] Building CXX object src/CMakeFiles/minetest.dir/client/clientmedia.cpp.o
make[2]: *** [src/CMakeFiles/minetest.dir/build.make:89: src/CMakeFiles/minetest.dir/client/client.cpp.o] Error 1
make[2]: *** Ожидание завершения заданий…
make[2]: *** [src/CMakeFiles/minetest.dir/build.make:115: src/CMakeFiles/minetest.dir/client/clientlauncher.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:746: src/CMakeFiles/minetest.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by AmyMoriyama** [comment]
I fixed it by using an older irrlicht version.

https://github.com/minetest/irrlicht/releases/tag/1.9.0mt3

**Comment by sangeet79** [comment]
it fixed the problem, thank you. I successfully tested dragonfire client at my own server :))))

**Comment by corarona** [comment]
fixed by merge of #49
