### ISSUE TITLE
Windows Build not working

### ISSUE THREAD

**Issue by samarth-ramesh** [dragonfireclient/dragonfireclient#5]
##### Minetest version
```
5.4 ( from your release)
```

##### OS / Hardware

Operating system: WIN-8
CPU:  intel i5 4200

##### Summary
The application refuses to start, and complains: 
![image](https://user-images.githubusercontent.com/50248419/94507475-784c9200-022d-11eb-954d-fccfbe589c9a.png)

##### Steps to reproduce
download the "release" zip, unzip it, and try running the executable

**Comment by arydevy** [comment]
you installed the reqered libs?
@samarth-ramesh

**Comment by samarth-ramesh** [comment]
yes, i had all the .ddl's in the same folder as the ,exe

**Comment by LizzyFleckenstein03** [comment]
Yea i don't really know why that happens. (I'm not very experienced with Windows)

**Comment by wsor4035** [comment]
https://www.youtube.com/watch?v=B4QnlJozFoM
should guide you through compiling for windows

**Comment by LizzyFleckenstein03** [comment]
tysm, will try it out!

**Comment by wsor4035** [comment]
@EliasFleckenstein03 also check out minetest CI on gitlabs, and you can modify it for your project, if you want compiled releases for each commit

**Comment by LizzyFleckenstein03** [comment]
The problem is not compiling on windows. The problem is creating a portable Windows build. (Which is actually not possible on Windows itself, you have to use cross-compiling using the build bot)

**Comment by LizzyFleckenstein03** [comment]
Try the new build, maybe that one works.

**Comment by ChefZander** [comment]
I got that Error too, Just use the mt 5.3.0 dlls

**Comment by LizzyFleckenstein03** [comment]
Fixed
