### ISSUE TITLE
filling tool

### ISSUE THREAD

**Issue by tigercoding56** [dragonfireclient/dragonfireclient#54]
## Problem

A clear and concise description of what the problem is.
ie: Why is this needed?
 I'm always frustrated when  i am building a large structure but need to rightklick thousands of times in order to build the floor

## Solutions

there is a mod called filler tool which allows you to select pos1 and pos2 and fills it with nodes until you run out of nodes 
a extended version of this could be added which could also have a circle mode , a sphere mode , a triangle mode , and a schematic autobuild mode , it should also be able to mine and follow crafting chains (bonus points for complicated ones such as the ones found in the techage modepack ) to get materials it needs to build 

## Alternatives

allow user to make scripts that control player via ingame  editor 

## Additional context

None

**Comment by corarona** [comment]
Sounds like that can all be done in a CSM,

that autobuild part is just quite complex to make.
