### ISSUE TITLE
Use Git Repository to Replace PostgreSQL Database

### ISSUE THREAD

**Issue by Pantyhose-X** [dragonfireclient/dragonfireclient#58]
[snowyu](https://github.com/snowyu) Carefully designed programs https://github.com/minetest/contentdb/issues/424

Completely abandon the dependency on the official content.minetest.net
## Current Status
dragonfireclient mods will never be added to content.minetest.net by the administrator,
This hinders the development of dragonfireclient mods.

**Comment by LizzyFleckenstein03** [comment]
meow
