### ISSUE TITLE
hey so this happened while i was trying to connect to a server

### ISSUE THREAD

**Issue by Ketnlas** [dragonfireclient/dragonfireclient#68]
Access denied. Reason: Lua: Runtime error from mod 'autoeat' in callback environment_step(): autoeat:init.lua:67: attempt to index local 'player' (a nil value)
stack traceback:
	autoeat:init.lua:67: in function 'func'
	*builtin*:common/after.lua:20: in function <*builtin*:common/after.lua:5>
	*builtin*:client/register.lua:25: in function <*builtin*:client/register.lua:13>

tell me if you need smtn from my part to fix this like info of the client.

note: i have no idea how to code
steps to reproduce: open dragonfireclient.exe with wine then go to join and then join a server.
note: im on linux mint

**Comment by corarona** [comment]
This is an issue in the autoeat mod to stop it from happening you can disable said mod. 

I have opened an issue there with your info:
https://github.com/dragonfireclient/autoeat/issues/1
