### ISSUE TITLE
New hack and Better GUI

### ISSUE THREAD

**Issue by Code-Sploit** [dragonfireclient/dragonfireclient#7]
## Problem

I would like to have speedhack added to Hack GUI
Also i would like to set the xray node in the gui

**Comment by Impxr** [comment]
How do I download the dragonfireclient?and I put it in the game

**Comment by LizzyFleckenstein03** [comment]
> How do I download the dragonfireclient?and I put it in the game

Dragonfireclient is an own version of minetest, therefore you cant install it on top of an already existing minetest installation. Please open a new issue for this and give more information (Which OS you are using).

**Comment by LizzyFleckenstein03** [comment]
> I would like to have speedhack added to Hack GUI

What do you mean by speedhack? Fast Mode? Fly & Fast & Noclip are a single cheat called PrivBypass.

> Also i would like to set the xray node in the gui

Actually you can have multible xray nodes now. Just use .xray add <node> and .xray del <node>
About the GUI thingy, how should it be done via GUI? I'm open to any suggestions.

**Comment by Code-Sploit** [comment]
Well since you can set the xray node with .xray add and .xray del, i will close that issue.
About the speedhack, i mean incresing normal walkspeed without the annoying effect.

It starts with this line is in src/client/localplayer.cpp

`accelerate((speedH + speedV) * physics_override_speed`

I changed it yesterday to use speedhack.

**Comment by Code-Sploit** [comment]
I also have a new request, (btw i am working on it myself right now):
A list of enabled hacks/cheats on your screen.

**Comment by LizzyFleckenstein03** [comment]
> I would like to have speedhack added to Hack GUI

Its called PrivBypass. Then just enable fast mode.
