### ISSUE TITLE
Add NodeESP

### ISSUE THREAD

**Issue by Code-Sploit** [dragonfireclient/dragonfireclient#9]
## Problem

Could you please add ChestESP and give the highliting another color?

**Comment by LizzyFleckenstein03** [comment]
My plan for NodeESP in general is: A configurable list, like X-Ray, where you can add / remove node to the list, two entries in the Cheat Menu (Search and SearchTracers), and the highlighting color for every node will be determined by its Minimap Color. filtering the nodes for Searched ones will be done by the MapBlock mesh generator and stored in the MapBlocks themselves.

But it will probably take some time until that feature is done....

**Comment by LizzyFleckenstein03** [comment]
I added NodeESP :)
